// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyUhTKNFFDmfUJkCrJ8v5656dd53Abt0Q',
    appId: '1:168767102842:web:8b8fa518b38424aab3c0c3',
    messagingSenderId: '168767102842',
    projectId: 'didi-auth',
    authDomain: 'didi-auth.firebaseapp.com',
    databaseURL: 'https://didi-auth-default-rtdb.firebaseio.com',
    storageBucket: 'didi-auth.appspot.com',
    measurementId: 'G-NRNDXZ5RYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaPCgsgBEA7F4YHSWd0k0Fkm155IxsX-A',
    appId: '1:168767102842:android:80f4845e876d1c12b3c0c3',
    messagingSenderId: '168767102842',
    projectId: 'didi-auth',
    databaseURL: 'https://didi-auth-default-rtdb.firebaseio.com',
    storageBucket: 'didi-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAlDFSm9DJu7kZdQCNhbD-F2-XQaUtnYk',
    appId: '1:168767102842:ios:345e2fd8316542ccb3c0c3',
    messagingSenderId: '168767102842',
    projectId: 'didi-auth',
    databaseURL: 'https://didi-auth-default-rtdb.firebaseio.com',
    storageBucket: 'didi-auth.appspot.com',
    iosBundleId: 'com.didicab.didiportal',
  );
}
